using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bookanizer.REST.DAL.Models
{
    [Table("genres")]
    public class GenreModel
    {
        #region Constructors
        public GenreModel()
        {
            GenreId = 0;
            Name = string.Empty;
            Books = new List<BookModel>();
        }

        public GenreModel(
            string name)
        {
            GenreId = 0; // Generated by DB
            Name = name;
            Books = new List<BookModel>();
        }
        #endregion

        #region Properties
        [Column("genre_id")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int GenreId { get; set; }

        [Column("name")]
        [Required]
        [MaxLength(256)]
        public string Name { get; set; }

        public ICollection<BookModel> Books { get; set; }
        #endregion

        #region Methods
        public void Update(GenreModel model)
        {
            Name = model.Name;
        }
        #endregion
    }
}
